version: '3.8'

services:
  automation-service:
    image: ubuntu-webarena-lite-v2-test:1.0
    container_name: ubuntu-webarena-lite-v2-test
    ports:
      - "${SERVICE_PORT:-9000}:9000"
      - "${VNC_PORT:-5900}:5900"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - SHOPPING=${SHOPPING}
      - SHOPPING_ADMIN=${SHOPPING_ADMIN}
      - REDDIT=${REDDIT}
      - GITLAB=${GITLAB}
      - MAP=${MAP}
    restart: unless-stopped
#    volumes:
#      - ./data:/app/data
    deploy:
      resources:
        limits:
          cpus: 4.0
          memory: 8G
        reservations:
          cpus: 4.0
          memory: 4G
