planner_model: 
  engine_type: openai
  model: scalecua
  base_url: http://10.140.60.1:8003/v1
  grounding_width: 1920
  grounding_height: 1080
  resize_corrds: true
  prompt_template: config/prompt_template/ours_ubuntu.json
  enable_thinking: true
