planner_model: 
  engine_type: openai
  model: gpt-4o-2024-11-20
  base_url: https://api.boyuerichdata.opensphereai.com/v1
  prompt_template: config/prompt_template/gpt_planner.json
ui_grounding_model: 
  engine_type: openai
  model: gui_v123
  base_url: http://10.140.66.139:10026/v1
  prompt_template: config/prompt_template/ours_android.json
  resize_corrds: true